In [1]:
import astropy
from astropy import units as u
from astropy.time import Time

In [72]:
u.h.to(u.s,18.408) #converts hours to seconds

66268.8

In [11]:
u.min.to(u.s, 8.3) #converts minutes to seconds

498.00000000000006

In [36]:
u.day.to(u.s,16.49-15)-9227

49852.799999999996

In [81]:
mags = [0.6225,
0.6311,
0.6397,
0.6418,
0.6437,
0.6455,
0.6473,
0.6492,
0.651,
0.6528,
0.6547,
0.6565,
0.6583,
0.6601,
0.662,
0.6639,
0.6657,
0.6675,
0.6693,
0.6712,
0.673,
0.6749,
0.6767,
0.6785,
0.6804,
0.6822,
0.684,
0.6859,3.24
4.24
5.25
6.25
7.24
8.24
9.25
10.24
11.24
12.24
14.55
14.91
15.28
16.22
17.64
25.68
27.9
40.93
43.12
45.33
20.27
30.57
32.77
48.21
50.41
52.62
22.89
35.47
37.67
1.97
2.45
2.94
3.41
3.9
4.81
5.64
6.48
7.65
9.19
20.16
23.18
26.18
29.2
32.93
38.19
59.16
69.57
81.29
94
108.24
123.06
143.61
165.14
186.06
208.34
240.71
278.12
1.97
2.45
2.95
3.37
3.99
4.81
5.64
6.48
7.65
9.17
20.16
23.18
26.19
29.22
32.96
38.97
58.72
69.64
81.33
94.02
108.3
123.96
143.15
163.97
186.98
209.23
242.54
280.31

0.7014,
0.7032,
0.7051,
0.7069,
0.7087,
0.7105,
0.7124,
1.7407,
1.7851,
1.7931,
2.7341,
2.7557,
2.9086,
2.9176,
3.7266,
3.8531,
3.8613,
9.8622,
27.5763,
30.7511,
36.904,
56.5242,
64.5516,
]

In [ ]:
a=[]
for i in mags:
    a.append(u.h.to(u.s,i))
    print(u.h.to(u.s,i))

In [ ]:
6:14:24

In [2]:
mags=[2.48,
2.49,
2.52,
2.53,
2.74,
3.45,
3.53,
3.71,
6.51,
7.91,
8.85,
9.89,
13.9,
14.85,
16.03,
18.01,
20.48,
20.51,
21.41,
23.54,
26.6,
26.61,
35.52,
45.47,
45.5,
]
a=[]
for i in mags:
    print(u.day.to(u.s, i))


214272.0
215136.00000000003
217728.0
218591.99999999997
236736.00000000003
298080.0
304992.0
320544.0
562464.0
683424.0
764640.0
854496.0
1200960.0
1283040.0
1384992.0
1556064.0000000002
1769472.0
1772064.0000000002
1849824.0
2033856.0
2298240.0
2299104.0
3068928.0000000005
3928608.0
3931200.0


In [111]:
x = 16.49 -15
u.day.to(u.s, x) - 9223.19#converts days to seconds

119512.80999999987

In [110]:
14.56*60

873.6

In [113]:
52.3*3600

188280.0

In [114]:
1.229*86400

106185.6

In [106]:
2110168.81+3600

2113768.81

In [78]:
66268.8 + 86400 - 44288.63


108380.16999999998

In [44]:
40383.370000000046+300

40683.370000000046

In [5]:
def midt(tstart,tstop):
    frac = (tstop - tstart)/2
    midt = tstart + frac
    return midt

In [54]:
midt(7484,18646)

13065.0

In [28]:
1.96*86400

169344.0

In [5]:
(415.43+573.11)/2.0

494.27

In [2]:
3*3600

10800

In [4]:
13*60 + 10800

11580

In [46]:
7279 + (197/2)

7377.5

In [32]:
from datetime import datetime

# start time
start_time = "19:18:43.00"
end_time = "19:51:22.00"

# convert time string to datetime
t1 = datetime.strptime(start_time, "%H:%M:%S.%f")
print('Start time:', t1.time())

t2 = datetime.strptime(end_time, "%H:%M:%S.%f")
print('End time:', t2.time())

# get difference    
delta = t2 - t121.16,
21.62,
21.94,
22.14,
22.34,
22.53,
22.86,
23.32,
23.78,
24.21,
24.64,
25.07,
25.5,
25.93,
26.36,
26.8,
27.25,
27.66,
28.08,
107.89,
109.58,
111.42,
113.25,
114.64,
370.07,
21.16,
21.62,
21.94,
22.14,
22.34,
22.53,
22.86,
23.32,
23.78,
24.21,
24.64,
25.07,
25.5,
25.93,
26.36,
26.8,
27.25,
27.66,
28.08,
107.89,
109.58,
111.42,
113.25,
114.64,
370.07,
21.16,
21.62,
21.94,
22.14,
22.34,
22.53,
22.86,
23.32,
23.78,
24.21,
24.64,
25.07,
25.5,
25.93,
26.36,
26.8,
27.25,
27.66,
28.08,
107.89,
109.58,
111.42,
113.25,
114.64,
370.07,
21.16,
21.62,
21.94,
22.14,
22.34,
22.53,
22.86,
23.32,
23.78,
24.21,
24.64,
25.07,
25.5,
25.93,
26.36,
26.8,
27.25,
27.66,
28.08,
107.89,
109.58,
111.42,
113.25,
114.64,
370.07,
21.19,
21.64,
22.26,
22.89,
23.35,
23.8,
24.23,
24.66,
25.09,
25.52,
25.96,
26.39,
26.82,
27.25,
27.68,
28.11,
28.52,
28.92,
29.33,
29.74,
30.14,
107.92,
109.61,
111.44,
113.28,
21.19,
21.64,
22.26,
22.89,
23.35,
23.8,
24.23,
24.66,
25.09,
25.52,
25.96,
26.39,
26.82,
27.25,
27.68,
28.11,
28.52,
28.92,
29.33,
29.74,
30.14,
30.54,
30.94,
107.92,
109.61,
21.19,
21.64,
22.26,
22.89,
23.35,
23.8,
24.23,
24.66,
25.09,
25.52,
25.96,
26.39,
26.82,
27.25,
27.68,
28.11,
28.52,
28.92,
29.33,
29.74,
30.14,
30.54,
30.94,
107.92,
109.61
ms = delta.total_seconds() * 1000
print(f"Time difference is {ms} milliseconds")

Start time: 19:18:43
End time: 19:51:22
Time difference is 1959.0 seconds
Time difference is 1959000.0 milliseconds


In [19]:
(28-15)*86400 + 29180.81 + (1919.99/2)

1153340.8050000002

times = ["13:13:04.0",
"13:20:05.0",
"13:27:05.0",
"15:07:22.0",
"16:09:02.0",
"16:27:48.0",
"19:57:08.0",
"14:38:52.0",
"14:52:56.0",
"16:03:40.0",
"16:14:57.0",
"16:33:28.0",
"12:51:20.0",
"12:58:21.0",
"13:05:23.0",
"14:32:51.0",
"15:16:15.0",
"15:49:32.0",
"15:54:56.0",
"16:19:59.0",
"16:39:30.0",
"16:46:28.0",
"20:02:54.0",
"20:09:25.0"
]

for i in times:
    fn("12:18:08.63",i)

In [66]:
86400*12 + 35936.37

1072736.37

In [34]:
86400-25666.63


60733.369999999995

In [57]:
t1.toordinal()

693596

In [40]:
t1

datetime.datetime(1900, 1, 1, 1, 12, 15)

In [36]:
84 + (10/2)

89.0

In [ ]:
84s

In [10]:
import pandas as pd

In [18]:
d = pd.read_csv('delete.txt', sep='\s+',names=['time', 'g', 'r','i'])

In [19]:
d

time      g      r      i
0     73.2  17.80  17.79  17.67
1    103.2  17.80  18.16  17.86
2    157.6  17.91  16.81  16.96
3    202.6  17.76  16.63  16.75
4    247.6  17.94  16.86  16.85
5    292.6  17.89  17.29  16.87
6    337.6  17.76  17.02  17.01
7    382.6  18.21  17.31  17.05
8    427.6  18.07  17.49  17.16
9    472.6  18.08  17.56  17.29
10   517.6  18.31  17.60  17.48
11   562.6  18.14  17.90  17.66
12   607.6  18.61  18.00  17.49
13   652.6  18.20  18.13  17.85
14   697.6  18.20  18.37  18.00
15   742.6  18.20  18.53  18.02
16   787.6  18.20  18.45  18.06
17   832.6  18.20  18.41  18.34
18   877.6  18.20  18.71  17.90
19   922.6  18.20  18.85  18.21
20   967.6  18.20  18.20  18.26
21  1012.6  18.20  18.20  17.80
22  1057.6  18.20  18.20  17.80
23  1102.6  18.20  18.20  17.80
24  1147.6  18.20  18.20  17.80
25  1192.6  18.20  18.30  17.80

In [23]:
d1 = [d['time'],d['g']]

In [27]:
d1 = d.loc[:,['time','g']]
d1 = d1.drop()

In [29]:
d1.to_csv('dd.txt', sep='\t')

import numpy as np
a = np.array([3.24,
4.24,
5.25,
6.25,
7.24,
8.24,
9.25,
10.24,
11.24,
12.24,
14.55,
14.91,
15.28,
16.22,
17.64,
25.68,
27.9,
40.93,
43.12,
45.33,
20.27,
30.57,
32.77,
48.21,
50.41,
52.62,
22.89,
35.47,
37.67,
1.97,
2.45,
2.94,
3.41,
3.9,
4.81,
5.64,
6.48,
7.65,
9.19,
20.16,
23.18,
26.18,
29.2,
32.93,
38.19,
59.16,
69.57,
81.29,
94,
108.24,
123.06,
143.61,
165.14,
186.06,
208.34,
240.71,
278.12,
1.97,
2.45,
2.95,
3.37,
3.99,
4.81,
5.64,
6.48,
7.65,
9.17,
20.16,
23.18,
26.19,
29.22,
32.96,
38.97,
58.72,
69.64,
81.33,
94.02,
108.3,
123.96,
143.15,
163.97,
186.98,
209.23,
242.54,
280.31,
])
b = np.array([60.2,60.2,
60.2,
59.4,
60.2,
60.2,
59.4,
60.2,
60.2,
58.9,
10,
10,
10,
20,
120,
120,
120,
120,
120,
120,
120,
120,
120,
120,
120,
120,
120,
120,
120,
20,
20,
20,
20,
20,
40,
40,
40,
80,
80,
160,
160,
160,
160,
240,
320,
560,
560,
560,
640,
800,
720,
880,
1040,
1040,
1040,
2080,
1520,
20,
20,
20,
10,
40,
40,
40,
40,
80,
80,
160,
160,
160,
160,
240,
240,
560,
560,
560,
640,
800,
800,
800,
880,
800,
800,
1360,
1040])

In [10]:
for i in range(len(a)):
    print(a[i]*60 + (b[i]/2.0))

224.5
284.5
345.1
404.7
464.50000000000006
524.5
584.7
644.5
704.5
763.85
878.0
899.6
921.8
983.1999999999999
1118.4
1600.8
1734.0
2515.8
2647.2
2779.7999999999997
1276.2
1894.2
2026.2000000000003
2952.6
3084.6
3217.2
1433.4
2188.2
2320.2000000000003
128.2
157.0
186.4
214.60000000000002
244.0
308.59999999999997
358.4
408.8
499.0
591.4
1289.6
1470.8
1650.8
1832.0
2095.8
2451.3999999999996
3829.6
4454.2
5157.400000000001
5960.0
6894.4
7743.6
9056.6
10428.4
11683.6
13020.4
15482.6
17447.2
128.2
157.0
187.0
207.20000000000002
259.4
308.59999999999997
358.4
408.8
499.0
590.2
1289.6
1470.8
1651.4
1833.1999999999998
2097.6000000000004
2458.2
3803.2
4458.4
5159.8
5961.2
6898.0
7837.599999999999
8989.0
10278.2
11618.8
12953.8
15232.4
17338.6


In [18]:
a = np.array([62,
62,
6130,
1682,
7810,
1608,
5926,
273,
273,
5720,
1731,
12921,
1706,
12014,
1658,
6336
])
b = np.array([147,
205,
1112,
58,
926,
58,
1967,
28,
66,
1967,
39,
1511,
58,
885,
58,
242
])
a*86400 + b/2

array([5.35687350e+06, 5.35690250e+06, 5.29632556e+08, 1.45324829e+08,
       6.74784463e+08, 1.38931229e+08, 5.12007384e+08, 2.35872140e+07,
       2.35872330e+07, 4.94208984e+08, 1.49558420e+08, 1.11637516e+09,
       1.47398429e+08, 1.03801004e+09, 1.43251229e+08, 5.47430521e+08])

In [28]:
a = np.array([139,
4734,
606,
351,
729,
704,
656])
b = np.array([147,
197,
58,
304,
452,
432,
1179
])

for i in range(len(a)):
    print(a[i] + b[i]/2.0)

212.5
4832.5
635.0
503.0
955.0
920.0
1245.5


In [36]:
a = np.array([0.07142,
0.07564,
0.07916,
0.08268,
0.08619,
0.09041,
0.09393,
0.0992,
0.10694,
0.11432,
0.12171,
0.12908]
)
for i in range(len(a)):
    print(a[i]*86400)

6170.688
6535.296
6839.423999999999
7143.552000000001
7446.816
7811.424
8115.552
8570.88
9239.616
9877.248
10515.744
11152.512


In [47]:
a = np.array([96	,
115	,
120	,
126	,
131	,
155	,
173	,
179	,
184	,
190	,
261	,
304	,
362	,
376	,
752	,
2035	
])
b = np.array([30	,
5	,
5	,
5	,
5	,
30	,
5	,
5	,
5	,
5	,
5	,
30	,
30	,
30	,
460	,
300	
])/2

In [48]:
for i in range(len(a)):
    print(a[i] + b[i])

111.0
117.5
122.5
128.5
133.5
170.0
175.5
181.5
186.5
192.5
263.5
319.0
377.0
391.0
982.0
2185.0


In [53]:
a = np.array([77	,
620	,
545	,
289	,
4113	,
3908	,
595
])
b = np.array([147	,
20	,
20	,
246	,
197	,
197	,
20	,
])

a + (b/2.0)

array([ 150.5,  630. ,  555. ,  412. , 4211.5, 4006.5,  605. ])

In [52]:
for i in a:
    print(i)

457.92
682.5600000000001
984.96
1382.4
1952.6399999999999
3058.56
4872.96
6808.32
56712.96
66381.12
1607860.8
2128282.56
16364082.24
65914.56
756898.56
1606296.96
1776314.8800000001
16362639.36
587.52
881.2800000000001
1226.88
1745.28
2436.48
3006.72
3689.28
4095.3599999999997
4449.599999999999
4950.719999999999
5650.56
6212.160000000001
6903.36
55581.119999999995
55702.08
55883.520000000004
65447.99999999999
1609416.0
2130053.7600000002
16365533.76
66856.32
16367019.84
518.4
50664.96000000001
285.12
319.68
354.24
777.5999999999999
1097.28
1563.8400000000001
2194.56
2825.28
3447.3599999999997
4008.9599999999996
4320.0
4769.28
5408.64
6030.72
6661.4400000000005
7473.599999999999
51693.12
54440.64
61076.159999999996


In [58]:
a = np.array([29.879537+30.022106,
30.007951+30.042095,
30.077613+30.163785,
30.096195+30.099667,
30.120174+30.205093
])
a*86400/2

array([2587750.9776, 2594161.9872, 2602428.3936, 2600461.2384,
       2606051.5344])